### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [angelojohngage/prj-rev-bwfs-dasmoto#6]
https://github.com/angelojohngage/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/style.css#L15-L37

You're repeating a lot of styles in these three CSS rules.

When you have some styles that need to get applied to several elements, write them in a single rule with a more general selector:

```css
* {
  font-family: Helvetica;
}

.product h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}
```
